server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://111.230.48.104:9411
feign:
  hystrix:
    enabled: true