server:
  port: 8763
spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://111.230.48.104:9411
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true