server:
  port: 8764
spring:
  application:
    name: service-ribbon
  zipkin:
    base-url: http://111.230.48.104:9411
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
logging:
  level:
    root: info
